### ISSUE TITLE
What should we do with this repo?

### ISSUE THREAD

**Issue by hellais** [torproject/tor#15]
Hello world,

Some time ago, the people that own this repo gave me maintainer rights and told me that we could do what we thought best with it.

I think some vague plan was discussed, but never executed.

If you want to be the leader of said Github ❤️ Tor plan, I would be very happy to follow and help you out 👍

**Comment by Jul10l1r4** [comment]
<h1>Hello World</h1>
<span>I would like to collaborate on this project :)</span>

**Comment by isislovecruft** [comment]
Hi @hellais! @teor2345 and @tlyu and I discussed this on IRC just now, and if you would be willing to make the three of us admins, we're intending to start devising a setup and guidelines for making this be an official mirror. (We _really_ like having TravisCI for tor.git on our personal repos, and we'd really like to figure out an easy way to have CI run on other people's PRs before merging! Also, we want to have more welcoming, friendly ways for folks to contribute!)

**Comment by hellais** [comment]
Hi @isislovecruft, thanks for picking this up.

I sent an invitation to the following github accounts to become "Owners" of the organisation:

* @isislovecruft 
* @tlyu 
* @teor2345

**Comment by tlyu** [comment]
Thanks @hellais !  It looks like all three of us have accepted the invitation so I'll close this issue now.
