### ISSUE TITLE
linux debian compile

### ISSUE THREAD

**Issue by knoxcard** [torproject/tor#155]
git clone
git checkout e22822e4ae75dc59c7242d84bc306476fbd92a3b
./autogen.sh
./configure --disable-asciidoc argument

checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking build system type... Invalid configuration `argument': machine `argument' not recognized
configure: error: /bin/bash ./config.sub argument failed

**Comment by Baccount** [comment]
@knoxcard Open a ticket on https://trac.torproject.org/projects/tor so this problem can be resolved faster.

**Comment by knoxcard** [comment]
I ended up doing an apt-get install tor instead
