### ISSUE TITLE
update the rsa key size! (1024 bit => 2048 bit)

### ISSUE THREAD

**Issue by chezsick** [torproject/tor#16]
hello/hi, i see my private key from my hidden service and i examined the code to search "rsa 1024" than the 1024 bit is weak and obsolete since 2010 i think, so update the rsa key size from 1024 bit to 2048 bit

**Comment by torproject-git** [comment]
If you have questions regarding Tor, please go to https://tor.stackexchange.com/ or the [tor-talk mailing list](https://lists.torproject.org/cgi-bin/mailman/listinfo/tor-talk) and ask a question.

**Comment by chezsick** [comment]
@torproject-git i accepted to send from tor-talk but when this is appear?
