### ISSUE TITLE
ports blocked/proxy / dynamic port switcher

### ISSUE THREAD

**Issue by simpletechnology** [torproject/tor#21]
please fix tor with dynamic port switcher that when recognizes tor ports are blocked, auto switch to another port,

this should fix issue with ports being blocked recently with proxy servers from USA ISP etc.

please submit fix to merlin also to have this done, as essentially theyre trying to disable our encryption here now sadly enough.

i suspect an dynamic port switcher would fix the issue.

thanks

Sean

**Comment by simpletechnology** [comment]
^_^

**Comment by simpletechnology** [comment]
standard tor not working with merlin, but tor client works find when using the proxy work around was testing done.

**Comment by simpletechnology** [comment]
thanks

**Comment by simpletechnology** [comment]
what i mean is the tor client on merlin would inject a new entry port if the default is blocked, etc.

doesnt seem to contain same features as the tor program client from tor.com which uses different proxies to connect

**Comment by qbi** [comment]
Please open a bug at https://trac.torproject.org/ or contact one of Tors support channel for help.
