### ISSUE TITLE
undefined reference to evdns_shutdown

### ISSUE THREAD

**Issue by themaddoctor** [torproject/tor#22]
Can't compile. Getting a linker error at the end of the build process that says
undefined reference to evdns_shutdown

The latest stable libevent (2.1.8) is installed.

**Comment by qbi** [comment]
Please open a bug at https://trac.torproject.org/ or contact one of Tors support channel for help.

**Comment by themaddoctor** [comment]
Are you affiliated with torproject?
Would you submit a bug for me? CAPTCHA failed to handle original
request, so I am unable to log in.
Thanks!


On 11/12/17, Jens Kubieziel <notifications@github.com> wrote:
> Closed #22.
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/torproject/tor/issues/22#event-1337772026


-- 
Thomas Kaeding

my public key: http://pgp.mit.edu/pks/lookup?op=get&search=0x81B0FCA32599BE6F

**Comment by themaddoctor** [comment]
never mind. it gave up and let me in


On 11/12/17, thomas kaeding <thomas.a.kaeding@gmail.com> wrote:
> Are you affiliated with torproject?
> Would you submit a bug for me? CAPTCHA failed to handle original
> request, so I am unable to log in.
> Thanks!
>
>
> On 11/12/17, Jens Kubieziel <notifications@github.com> wrote:
>> Closed #22.
>>
>> --
>> You are receiving this because you authored the thread.
>> Reply to this email directly or view it on GitHub:
>> https://github.com/torproject/tor/issues/22#event-1337772026
>
>
> --
> Thomas Kaeding
>
> my public key:
> http://pgp.mit.edu/pks/lookup?op=get&search=0x81B0FCA32599BE6F
>


-- 
Thomas Kaeding

my public key: http://pgp.mit.edu/pks/lookup?op=get&search=0x81B0FCA32599BE6F
