### ISSUE TITLE
debuild -rfakeroot -uc -us + tor source (PLS HELP!)

### ISSUE THREAD

**Issue by cokeflash** [torproject/tor#24]
Hi!

I want use cryptodev support on tor.

Try to compile new from source, added to debian/rules:

#!/usr/bin/make -f
# -*- makefile -*-

DH_VERBOSE ?= 1

DEB_HOST_ARCH_OS := $(shell dpkg-architecture -qDEB_HOST_ARCH_OS)

export DEB_BUILD_MAINT_OPTIONS = hardening=+all

# allow building against libdmalloc4 - it better be installed
ifneq (,$(findstring with-dmalloc,$(DEB_BUILD_OPTIONS)))
	confflags += --with-dmalloc
endif
# allow building with --enable-openbsd-malloc
ifneq (,$(findstring enable-openbsd-malloc,$(DEB_BUILD_OPTIONS)))
	confflags += --enable-openbsd-malloc
endif

ifeq ($(DEB_HOST_ARCH_OS),linux)
	dhoptions += --with systemd
	confflags += --enable-systemd
endif

%:
	dh \
		$@ \
		--with quilt \
		--with autoreconf \
		$(dhoptions) \
		--builddirectory=build \
		--parallel

override_dh_auto_configure:
    ! [ -e debian/micro-revision.i ] || cp debian/micro-revision.i src/or/micro-revision.i \
    dh_auto_configure -- \
            $(confflags) \
            --enable-static-openssl \
            --with-openssl-dir=/usr/local/ssl \
            --prefix=/usr \
            --mandir=\$${prefix}/share/man \
            --infodir=\$${prefix}/share/info \
            --localstatedir=/var \
            --sysconfdir=/etc \
            --disable-silent-rules

override_dh_clean:
	! [ -e debian/micro-revision.i ] || rm -f src/or/micro-revision.i

	# Normally the .deb wouldn't ship with a ../.git, but if we do, include the revision number
	if [ -d .git ] && which git >/dev/null; then \
		echo "\"`git rev-parse --short=16 HEAD`\"" > "debian/micro-revision.i" ; \
	fi

	# these get autobuilt from the .txt files, some of which we also patch
	rm -vf doc/*.in
	rm -f debian/tor-instance-create.8

	dh_clean

override_dh_auto_build:
	dh_auto_build
	a2x -f manpage debian/tor-instance-create.8.txt
	chmod +x debian/systemd/tor-generator

override_dh_install-arch:
	dh_install --fail-missing

	mv debian/tor/etc/tor/torrc.sample debian/tor/etc/tor/torrc

	cp debian/tor.apparmor-profile             debian/tor/etc/apparmor.d/system_tor
	cp debian/tor.apparmor-profile.abstraction debian/tor/etc/apparmor.d/abstractions/tor
	dh_apparmor --profile-name=system_tor -ptor

override_dh_strip:
	dh_strip --dbgsym-migration='tor-dbg (<< 0.3.1.5-alpha)'
override_dh_installinit:
	dh_installinit --error-handler=tor_error_init

in terminal output error:

debuild -rfakeroot -uc -us
 dpkg-buildpackage -rfakeroot -us -uc
dpkg-buildpackage: info: source package tor
dpkg-buildpackage: info: source version 0.3.0.10-1
dpkg-buildpackage: info: source distribution unstable
dpkg-buildpackage: info: source changed by Peter Palfrader <weasel@debian.org>
 dpkg-source --before-build tor-0.3.0.10
dpkg-buildpackage: info: host architecture amd64
 fakeroot debian/rules clean
debian/rules:34: *** missing separator.  Stop.
dpkg-buildpackage: error: fakeroot debian/rules clean gave error exit status 2
debuild: fatal error at line 1124:
dpkg-buildpackage -rfakeroot -us -uc failed

how to fix it?

**Comment by cokeflash** [comment]
make[1]: *** [test] Error 1
make[1]: Leaving directory '/home/nwo/debian-packages/tor-0.3.2.9/build'
dh_auto_test: make -j8 test VERBOSE=1 returned exit code 2
debian/rules:25: recipe for target 'build' failed
make: *** [build] Error 2
dpkg-buildpackage: error: debian/rules build gave error exit status 2
debuild: fatal error at line 1124:
dpkg-buildpackage -rfakeroot -us -uc failed

what does it mean?

**Comment by cokeflash** [comment]
I fix the error with:  DEB_BUILD_OPTIONS=nocheck debuild -rfakeroot -uc -us

but new error: 
no dependency information found for /usr/local/lib/libevent-2.1.so.6 

any idea?

**Comment by cokeflash** [comment]
make[1]: Entering directory '/home/nwo/debian-packages/tor-0.3.2.9'
dh_strip --dbgsym-migration='tor-dbg (<< 0.3.1.5-alpha)'
make[1]: Leaving directory '/home/nwo/debian-packages/tor-0.3.2.9'
   dh_makeshlibs -O--builddirectory=build -O--parallel
   dh_shlibdeps -O--builddirectory=build -O--parallel
dpkg-shlibdeps: error: no dependency information found for /usr/local/lib/libevent-2.1.so.6 (used by debian/tor/usr/bin/tor)
Hint: check if the library actually comes from a package.
dh_shlibdeps: dpkg-shlibdeps -Tdebian/tor.substvars debian/tor/usr/bin/tor-gencert debian/tor/usr/bin/tor debian/tor/usr/bin/tor-resolve returned exit code 2
dh_shlibdeps: Aborting due to earlier error
debian/rules:26: recipe for target 'binary' failed
make: *** [binary] Error 25
dpkg-buildpackage: error: fakeroot debian/rules binary gave error exit status 2
debuild: fatal error at line 1124:
dpkg-buildpackage -rfakeroot -us -uc failed
 :-(

**Comment by cokeflash** [comment]
"SOLVED"

in debian/rules:

add:
DEB_CONFIGURE_EXTRA_FLAGS += --without-included-regex --with-gnu-ld
export DEB_DH_SHLIBDEPS_ARGS_ALL=--dpkg-shlibdeps-params=--ignore-missing-info

edit:
/usr/bin/dpkg-shlibdeps

my $ignore_missing_info = 1;                      ## from 0 to 1

DEB_BUILD_OPTIONS=nocheck debuild -rfakeroot -uc -us

cd ..

sudo dpkg -i tor_*.deb

**Comment by tlyu** [comment]
It looks like you resolved your issue.  In the future, please file bug reports on trac.torproject.org.  We don't use GitHub issues for this repository.  Thanks.
